services:
  spring-app:
    build: .
    container_name: my-spring-app
    ports:
      - "8080:8080"
    depends_on:
      - redis

  # Redis 설정
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

volumes:
  redis_data:
