spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # snake_case -> camelCase 매핑
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
